#!/usr/bin/env python3
"""Plot the CsPbI3 phase diagram from a free_energy_ti phase_diagram.csv file."""

from __future__ import annotations

import argparse
import csv
import math
import os
from pathlib import Path
from typing import Dict, List, Optional

os.environ.setdefault(
    "MPLCONFIGDIR",
    str(Path(os.environ.get("TMPDIR", "/tmp")) / "transformers-ace-matplotlib"),
)
os.environ.setdefault("MPLBACKEND", "Agg")

import matplotlib.pyplot as plt
import numpy as np


SCRIPT_DIR = Path(__file__).resolve().parent
EV_TO_KJ_MOL = 96.48533212331002


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data",
        type=Path,
        default=SCRIPT_DIR / "runs" / "production" / "results" / "phase_diagram.csv",
        help="Input phase_diagram.csv generated by run_ti.py",
    )
    parser.add_argument(
        "--output-prefix",
        type=Path,
        default=SCRIPT_DIR / "runs" / "production" / "results" / "phase_diagram_custom",
        help="Output path without an extension; both PNG and PDF are written",
    )
    parser.add_argument("--formula-atoms", type=int, default=5)
    parser.add_argument("--reference-temperature", type=float, default=300.0)
    parser.add_argument("--experimental-temperature", type=float, default=600.0)
    parser.add_argument("--xmin", type=float, default=400.0)
    parser.add_argument("--xmax", type=float, default=650.0)
    parser.add_argument("--xtick-step", type=float, default=50.0)
    parser.add_argument("--ymin-difference", type=float, default=-6.0)
    parser.add_argument("--ymax-difference", type=float, default=None)
    parser.add_argument("--font-size", type=float, default=22.0)
    parser.add_argument("--label-size", type=float, default=32.0)
    parser.add_argument("--title-size", type=float, default=28.0)
    parser.add_argument("--tick-size", type=float, default=22.0)
    parser.add_argument("--legend-size", type=float, default=22.0)
    parser.add_argument("--width", type=float, default=16.5)
    parser.add_argument("--height", type=float, default=6.8)
    parser.add_argument("--dpi", type=int, default=300)
    parser.add_argument("--delta-color", default="#2f6f9f")
    parser.add_argument("--cubic-color", default="#d46a3a")
    parser.add_argument("--difference-color", default="#6a3d9a")
    parser.add_argument("--experimental-color", default="#c4513e")
    parser.add_argument("--hide-ci", action="store_true")
    parser.add_argument("--hide-experimental", action="store_true")
    parser.add_argument("--hide-transition-label", action="store_true")
    return parser.parse_args()


def read_table(path: Path) -> Dict[str, np.ndarray]:
    required = {
        "temperature_K",
        "g_delta_eV_atom",
        "g_cubic_eV_atom",
        "delta_g_delta_minus_cubic_kJ_mol_fu",
        "ci_low_kJ_mol_fu",
        "ci_high_kJ_mol_fu",
    }
    with path.expanduser().resolve().open(newline="") as handle:
        rows: List[dict] = list(csv.DictReader(handle))
    if not rows:
        raise ValueError("No rows found in {}".format(path))
    missing = required.difference(rows[0])
    if missing:
        raise ValueError("Missing CSV columns: {}".format(", ".join(sorted(missing))))
    return {
        name: np.asarray([float(row[name]) for row in rows], dtype=float)
        for name in required
    }


def value_at_temperature(
    temperatures: np.ndarray, values: np.ndarray, target: float
) -> float:
    matches = np.flatnonzero(np.isclose(temperatures, target, atol=1.0e-8))
    if len(matches) != 1:
        raise ValueError(
            "Reference temperature {:g} K must occur exactly once in the CSV".format(target)
        )
    return float(values[matches[0]])


def crossing_temperature(
    temperatures: np.ndarray, delta_g: np.ndarray
) -> Optional[float]:
    exact = np.flatnonzero(np.isclose(delta_g, 0.0, atol=1.0e-14))
    if len(exact):
        return float(temperatures[exact[0]])
    for index in range(len(temperatures) - 1):
        left, right = float(delta_g[index]), float(delta_g[index + 1])
        if left * right < 0.0:
            fraction = -left / (right - left)
            return float(
                temperatures[index]
                + fraction * (temperatures[index + 1] - temperatures[index])
            )
    return None


def main() -> None:
    args = parse_args()
    if args.formula_atoms <= 0:
        raise ValueError("--formula-atoms must be positive")
    if args.xmax <= args.xmin:
        raise ValueError("--xmax must be greater than --xmin")
    if args.xtick_step <= 0.0:
        raise ValueError("--xtick-step must be positive")

    table = read_table(args.data)
    order = np.argsort(table["temperature_K"])
    temperature = table["temperature_K"][order]
    g_delta = table["g_delta_eV_atom"][order]
    g_cubic = table["g_cubic_eV_atom"][order]
    delta_g = table["delta_g_delta_minus_cubic_kJ_mol_fu"][order]
    ci_low = table["ci_low_kJ_mol_fu"][order]
    ci_high = table["ci_high_kJ_mol_fu"][order]

    conversion = float(args.formula_atoms) * EV_TO_KJ_MOL
    reference = value_at_temperature(
        temperature, g_cubic, args.reference_temperature
    )
    relative_delta = (g_delta - reference) * conversion
    relative_cubic = (g_cubic - reference) * conversion
    crossing = crossing_temperature(temperature, delta_g)

    plt.rcParams.update(
        {
            "font.size": args.font_size,
            "axes.labelsize": args.label_size,
            "axes.titlesize": args.title_size,
            "xtick.labelsize": args.tick_size,
            "ytick.labelsize": args.tick_size,
            "legend.fontsize": args.legend_size,
            "axes.linewidth": 1.2,
        }
    )
    figure, axes = plt.subplots(
        1, 2, figsize=(args.width, args.height), constrained_layout=True
    )

    axes[0].plot(
        temperature,
        relative_delta,
        "o-",
        lw=2.0,
        ms=5.5,
        color=args.delta_color,
        label=r"$\delta$-CsPbI$_3$",
    )
    axes[0].plot(
        temperature,
        relative_cubic,
        "o-",
        lw=2.0,
        ms=5.5,
        color=args.cubic_color,
        label=r"$\alpha$-CsPbI$_3$",
    )
    axes[0].set_xlabel("Temperature (K)")
    axes[0].set_ylabel(
        r"$G(T)-G_{\alpha}(%g\,\mathrm{K})$ (kJ mol$^{-1}$ f.u.$^{-1}$)"
        % args.reference_temperature
    )
    axes[0].legend(frameon=False)

    axes[1].axhline(0.0, color="0.25", lw=1.1)
    axes[1].plot(
        temperature,
        delta_g,
        "o-",
        color=args.difference_color,
        lw=2.2,
        ms=5.5,
    )
    if not args.hide_ci:
        axes[1].fill_between(
            temperature,
            ci_low,
            ci_high,
            color=args.difference_color,
            alpha=0.18,
            linewidth=0,
        )
    if crossing is not None:
        axes[1].axvline(crossing, color="0.35", ls="--", lw=1.2)
        if not args.hide_transition_label:
            axes[1].annotate(
                r"$T_{\mathrm{TRACE}}=%.0f$ K" % crossing,
                xy=(crossing, 0.0),
                xytext=(crossing - 18.0, 1.15),
                ha="right",
                va="bottom",
                fontsize=args.font_size,
                arrowprops={"arrowstyle": "-", "color": "0.35", "lw": 1.0},
            )
    if not args.hide_experimental:
        axes[1].axvline(
            args.experimental_temperature,
            color=args.experimental_color,
            ls=":",
            lw=1.6,
        )
        axes[1].text(
            0.50,
            0.20,
            r"$T_{\mathrm{exp}}\simeq %g\,\mathrm{K}$"
            % args.experimental_temperature,
            transform=axes[1].transAxes,
            ha="center",
            va="bottom",
            fontsize=args.font_size,
            color=args.experimental_color,
        )
    axes[1].set_xlabel("Temperature (K)")
    axes[1].set_ylabel(
        r"$G_{\delta}-G_{\alpha}$ (kJ mol$^{-1}$ f.u.$^{-1}$)"
    )
    if args.ymin_difference is not None or args.ymax_difference is not None:
        axes[1].set_ylim(args.ymin_difference, args.ymax_difference)

    ticks = np.arange(
        args.xmin, args.xmax + 0.5 * args.xtick_step, args.xtick_step
    )
    for axis in axes:
        axis.set_xlim(args.xmin, args.xmax)
        axis.set_xticks(ticks)
        axis.tick_params(
            direction="in", top=True, right=True, width=1.1, length=5
        )

    output_prefix = args.output_prefix.expanduser().resolve()
    output_prefix.parent.mkdir(parents=True, exist_ok=True)
    png_path = output_prefix.with_suffix(".png")
    pdf_path = output_prefix.with_suffix(".pdf")
    figure.savefig(png_path, dpi=args.dpi)
    figure.savefig(pdf_path)
    plt.close(figure)

    print("Read {}".format(args.data.expanduser().resolve()))
    print("Wrote {}".format(png_path))
    print("Wrote {}".format(pdf_path))
    if crossing is None or not math.isfinite(crossing):
        print("No zero crossing occurs inside the sampled temperature interval")
    else:
        print("Linear-interpolation crossing: {:.3f} K".format(crossing))


if __name__ == "__main__":
    main()
